#!/bin/bash

function hash() {
    # Linux sha256
    if [[ -x "$(command -v sha256sum)" ]]; then
        sha256sum "$1" | awk '{print $1}'
    # BSD sha256
    elif [[ -x "$(command -v shasum)" ]]; then
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

export -f hash
